#!/bin/bash
# ==========================================
# Color
RED='\033[0;31m'
NC='\033[0m'
#GREEN='\033[0;32m'
#ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
#CYAN='\033[0;36m'
LIGHT='\033[0;37m'
off='\x1b[m'
# ==========================================

clear

#LICENSE
read -p "Masukan LICENSE Anda : " sub
echo "Cecking License for ${sub}..."
# Getting
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
#########################

BURIQ () {
    curl -sS https://autosc.me/a/b/c/d/f/g/h/i/j/k/l/m/n/allow > /root/tmp
    data=( `cat /root/tmp | grep -E "^### " | awk '{print $2}'` )
    for user in "${data[@]}"
    do
    exp=( `grep -E "^### $user" "/root/tmp" | awk '{print $3}'` )
    d1=(`date -d "$exp" +%s`)
    d2=(`date -d "$biji" +%s`)
    exp2=$(( (d1 - d2) / 86400 ))
    if [[ "$exp2" -le "0" ]]; then
    echo $user > /etc/.$user.ini
    else
    rm -f /etc/.$user.ini > /dev/null 2>&1
    fi
    done
    rm -f /root/tmp
}

MYIP=${sub}
Name=$(curl -sS https://autosc.me/a/b/c/d/f/g/h/i/j/k/l/m/n/allow | grep $sub | awk '{print $2}')
echo $Name > /usr/local/etc/.$Name.ini
CekOne=$(cat /usr/local/etc/.$Name.ini)

Bloman () {
if [ -f "/etc/.$Name.ini" ]; then
CekTwo=$(cat /etc/.$Name.ini)
    if [ "$CekOne" = "$CekTwo" ]; then
        res="Expired"
    fi
else
res="Permission Accepted..."
fi
}

PERMISSION () {
    MYIP=${sub}
    IZIN=$(curl -sS https://autosc.me/a/b/c/d/f/g/h/i/j/k/l/m/n/allow | awk '{print $4}' | grep $sub)
    if [ "$sub" = "$IZIN" ]; then
    Bloman
    else
    res="Permission Denied!"
    fi
    BURIQ
}
red='\e[1;31m'
green='\e[1;32m'
NC='\e[0m'
green() { echo -e "\\033[32;1m${*}\\033[0m"; }
red() { echo -e "\\033[31;1m${*}\\033[0m"; }
PERMISSION

if [ -f /home/needupdate ]; then
red "Your script need to update first !"
exit 0
elif [ "$res" = "Permission Accepted..." ]; then
green "License Acepted"

rm -r -f /var/lib/tes

mkdir /var/lib/tes

cd /var/lib/tes

git clone https://github.com/fsidvpn/perizinan.git

clear

#LICENSE                                                                        
apt install curl -y
su=$(curl -sS ipinfo.io/ip)                                           
echo "Registering Ip ${su}..."

subb="PREMI"$(</dev/urandom tr -dc 0-9 | head -c2)
echo "#& "$subb" Lifetime "$su >> /var/lib/tes/perizinan/main/allow

cd /var/lib/tes/perizinan/main

git add allow

git commit -m allow

git push -f https://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@github.com/fsidvpn/perizinan.git

clear

sleep 2

rm -r -f /etc/.$Name.ini

hem=figlet slant "IP BERHASIL DI DAFTARKAN"

echo -e $GREEN $hem

sleep 10

figlet -f slant "INSTALLING SCRIPT PLEASE WAIT" | lolcat
sleep 1
    rm -f setupp.sh && sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -w net.ipv6.conf.default.disable_ipv6=1 && apt update && apt upgrade -y && apt-get update -y && apt-get upgrade -y && apt install -y bzip2 gzip coreutils screen curl unzip && wget https://raw.githubusercontent.com/fsidvpn/vps/main/setupp.sh && chmod +x setupp.sh && sed -i -e 's/\r$//' setupp.sh && screen -S setupp ./setupp.sh

    rm -r -f License

else
red "License Tidak Ditemukan!"

cd

rm -r -f License

exit 0
fi

